USE portfolio;

INSERT INTO skills (name, level, category, icon)
VALUES
('Figma', 'expert', 'design', 'logos:figma'),
('HTML 5', 'expert', 'frontend', 'logos:html-5'),
('CSS 3', 'expert', 'frontend', 'logos:css-3'),
('Sass', 'expert', 'frontend', 'logos:sass'),
('BEM', '', 'other', 'logos:bem'),
('Tailwind', 'expert', 'frontend', 'logos:tailwindcss-icon'),
('Bootstrap', 'intermediate', 'frontend', 'logos:bootstrap'),
('JavaScript', 'expert', 'language', 'logos:javascript'),
('TypeScript', 'expert', 'language', 'logos:typescript-icon'),
('PHP', 'intermediate', 'language', 'logos:php'),
('Vue', 'expert', 'frontend', 'logos:vue'),
('Nuxt', 'expert', 'frontend', 'logos:nuxt-icon'),
('Vuetify', 'intermediate', 'frontend', 'logos:vuetifyjs'),
('React', 'intermediate', 'frontend', 'logos:react'),
('NextJS', 'beginner', 'frontend', 'logos:nextjs-icon'),
('Sencha', 'beginner', 'frontend', 'logos:sencha'),
('Pinia', 'expert', 'frontend', 'logos:pinia'),
('Redux', 'beginner', 'frontend', 'logos:redux'),
('Vite', 'intermediate', 'tooling', 'logos:vitejs'),
('NPM', 'expert', 'tooling', 'logos:npm-icon'),
('Node', 'expert', 'backend', 'logos:nodejs'),
('ExpressJS', 'intermediate', 'backend', 'skill-icons:expressjs-light'),
('Socket.IO', 'intermediate', 'backend', 'logos:socket-io'),
('Laravel', 'intermediate', 'backend', 'logos:laravel'),
('SQL', 'intermediate', 'database', 'logos:mysql'),
('MongoDB', 'intermediate', 'database', 'logos:mongodb-icon'),
('Supabase', 'intermediate', 'auth/cloud', 'logos:supabase-icon'),
('Firebase', 'intermediate', 'auth/cloud', 'logos:firebase'),
('GraphQL', 'intermediate', 'api', 'logos:graphql'),
('Insomnia', 'intermediate', 'api', 'logos:insomnia'),
('Postman', 'expert', 'api', 'logos:postman-icon'),
('Cypress', 'beginner', 'testing', 'logos:cypress-icon'),
('Jest', 'beginner', 'testing', 'logos:jest'),
('Handlebars', 'beginner', 'frontend', 'logos:handlebars'),
('jQuery', 'expert', 'frontend', 'skill-icons:jquery'),
('VS Code', 'expert', 'tooling', 'logos:visual-studio-code'),
('ESLint', 'expert', 'tooling', 'logos:eslint'),
('Prettier', 'intermediate', 'tooling', 'logos:prettier'),
('GitHub', 'expert', 'tooling', 'skill-icons:github-dark'),
('GitLab', 'expert', 'tooling', 'logos:gitlab'),
('Netlify', 'expert', 'deployment', 'skill-icons:netlify-light'),
('PWA', 'intermediate', 'frontend', 'logos:pwa')
ON DUPLICATE KEY UPDATE name = VALUES(name);
